import{ChildProcessWithoutNullStreams,spawn}from"node:child_process";import{basename}from"node:path";import{ReviewSourceState}from"./types";
export interface ProcessResult{command:string[];cwd:string;exitCode:number;stdout:string;stderr:string;cancelled?:boolean;timedOut?:boolean}
export interface ProcessOptions{timeoutMs?:number;signal?:AbortSignal;onStdoutLine?:(line:string)=>void;onStderrLine?:(line:string)=>void}
export function formatCommand(command:readonly string[]):string{return command.map(p=>/[\s"]/u.test(p)?JSON.stringify(p):p).join(" ")}
/** Spawn argv directly: command strings are never evaluated by a shell. */
function terminateProcessTree(child:ChildProcessWithoutNullStreams):void{if(child.exitCode!==null||!child.pid)return;if(process.platform==="win32"){const killer=spawn("taskkill",["/pid",String(child.pid),"/T","/F"],{shell:false,windowsHide:true,stdio:"ignore"});killer.unref();return}try{process.kill(-child.pid,"SIGTERM")}catch{child.kill("SIGTERM")}}
export function runProcess(executable:string,args:readonly string[],cwd:string,timeoutOrOptions:number|ProcessOptions=120_000):Promise<ProcessResult>{const options=typeof timeoutOrOptions==="number"?{timeoutMs:timeoutOrOptions}:timeoutOrOptions;const command=[executable,...args];return new Promise((resolve,reject)=>{let child:ChildProcessWithoutNullStreams;let cancelled=false,timedOut=false;try{child=spawn(executable,[...args],{cwd,shell:false,windowsHide:true,detached:process.platform!=="win32"})}catch(error){reject(error);return}let stdout="",stderr="",stdoutPending="",stderrPending="";const lines=(value:string,kind:"out"|"err")=>{const parts=value.split(/\r?\n/u);const pending=parts.pop()||"";for(const line of parts)(kind==="out"?options.onStdoutLine:options.onStderrLine)?.(line);return pending};const timer=setTimeout(()=>{timedOut=true;terminateProcessTree(child)},options.timeoutMs??120_000);const abort=()=>{cancelled=true;terminateProcessTree(child)};options.signal?.addEventListener("abort",abort,{once:true});child.stdout.on("data",(d:Buffer)=>{const text=d.toString();stdout+=text;stdoutPending=lines(stdoutPending+text,"out")});child.stderr.on("data",(d:Buffer)=>{const text=d.toString();stderr+=text;stderrPending=lines(stderrPending+text,"err")});child.on("error",error=>{clearTimeout(timer);options.signal?.removeEventListener("abort",abort);reject(error)});child.on("close",code=>{clearTimeout(timer);options.signal?.removeEventListener("abort",abort);if(stdoutPending)options.onStdoutLine?.(stdoutPending);if(stderrPending)options.onStderrLine?.(stderrPending);resolve({command,cwd,exitCode:code??-1,stdout,stderr,cancelled,timedOut})})})}
/** `--json` is a global CodeSlicer argument and must precede the subcommand. */
export function buildReviewArgs(workspace:string,source:ReviewSourceState,baseRef?:string):string[]{const args=["--json","review",workspace,"--source",source.mode];if(baseRef)args.push("--base",baseRef);if(source.diffFile)args.push("--diff-file",source.diffFile);return[...args,"--max-results","10","--run-tests","none","--refresh","auto","--no-daemon"]}
export function buildAnalyzeArgs(workspace:string):string[]{return["--json","analyze",workspace,"--use-scan-plan","--progress","jsonl","--no-daemon"]}
export function safeTestCommand(command:unknown):string[]|undefined{if(!Array.isArray(command)||!command.length||!command.every(x=>typeof x==="string"&&x.length>0&&!/[\0\r\n]/u.test(x)))return undefined;const argv=command as string[];const runner=basename(argv[0]).toLowerCase();return new Set(["py","py.exe","python","python.exe","pytest","pytest.exe","node","node.exe","npm","npm.cmd","npx","npx.cmd","dotnet","dotnet.exe","cargo","cargo.exe","go","go.exe"]).has(runner)?argv:undefined}
