"""Argument parser construction for the public CLI."""
from impact_engine.cli_support import *
from impact_engine import __version__


def build_parser(prog: str = "impact-engine") -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog=prog)
    parser.add_argument("--json", action="store_true", help="Output raw JSON results")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = parser.add_subparsers(dest="command")

    analyze = sub.add_parser("analyze")
    analyze.add_argument("path")
    analyze.add_argument("--out", default=None)
    analyze.add_argument("--local-registry", dest="remote_registry", action="store_true", help="Use the local SQLite registry")
    analyze.add_argument("--no-research-requests", action="store_true")
    analyze.add_argument("--graphify", default=None, help="Optional Graphify graph.json to normalize and merge")
    analyze.add_argument("--use-scan-plan", action="store_true", help="Create/reuse .impact_engine/scan_plan.json before analysis")
    analyze.add_argument("--full-resolution", action="store_true", help="Opt into unbounded semantic and precision resolution for large projects")
    analyze.add_argument("--scope", default=None, help="Workspace/package scope to analyze")
    analyze.add_argument("--progress", choices=["human", "jsonl"], default="human", help="Progress stream format; JSON Lines is written to stderr")
    analyze.add_argument("--no-daemon", action="store_true", help="Do not use the local daemon owner")

    onboard = sub.add_parser("onboard", help="Connect a local project or explicit Git URL and build separate CodeSlicer/Graphify graphs")
    onboard.add_argument("source", help="Existing local project directory or Git URL")
    onboard.add_argument("--allow-network", action="store_true", help="Explicitly allow git clone when source is a URL")
    onboard.add_argument("--workspace", default=None, help="Local directory for a URL clone; defaults to ~/.codeslicer/projects")
    onboard.add_argument("--branch", default=None, help="Optional branch for a Git URL clone")
    onboard.add_argument("--graphify", choices=["auto", "off", "required"], default="auto", help="Build a separate optional Graphify architecture graph")
    onboard.add_argument("--graphify-timeout", type=int, default=120)
    onboard.add_argument("--out", default=None, help="Optional copy of the onboarding JSON report")

    scan_plan = sub.add_parser("scan-plan", help="Plan the files and directories that will be analyzed")
    scan_plan.add_argument("path")
    scan_plan.add_argument("--json", action="store_true", dest="local_json")

    visualize = sub.add_parser("visualize")
    visualize.add_argument("graph", help="Path to graph.json")
    visualize.add_argument("--out", default=None, help="Output HTML path")

    compare = sub.add_parser("visualize-compare")
    compare.add_argument("impact_graph", help="Impact Engine graph.json")
    compare.add_argument("graphify_graph", help="Graphify graph.json")
    compare.add_argument("--out", default="graph_comparison.html", help="Output HTML path")

    incremental = sub.add_parser("analyze-incremental")
    incremental.add_argument("path")
    incremental.add_argument("--out", default=None)
    incremental.add_argument("--snapshot", default=None)
    incremental.add_argument("--changed", action="append", default=None)
    incremental.add_argument("--scope", default=None)
    incremental.add_argument("--no-daemon", action="store_true")

    watch = sub.add_parser("watch")
    watch.add_argument("path")
    watch.add_argument("--out", default=None)
    watch.add_argument("--interval", type=float, default=1.0)
    watch.add_argument("--iterations", type=int, default=1)
    watch.add_argument("--scope", default=None)
    watch.add_argument("--no-daemon", action="store_true")

    daemon = sub.add_parser("daemon", help="Manage the local persistent analysis owner")
    daemon_sub = daemon.add_subparsers(dest="daemon_command")
    daemon_start = daemon_sub.add_parser("start")
    daemon_start.add_argument("project")
    daemon_status_parser = daemon_sub.add_parser("status")
    daemon_status_parser.add_argument("project")
    daemon_stop = daemon_sub.add_parser("stop")
    daemon_stop.add_argument("project")

    agent = sub.add_parser("agent", help="Install bundled CodeSlicer skills and local MCP entries for AI clients")
    agent_sub = agent.add_subparsers(dest="agent_command")
    agent_detect = agent_sub.add_parser("detect", help="Detect locally configured AI clients without writing files")
    agent_detect.add_argument("--project", default=".")
    agent_detect.add_argument("--json", action="store_true", dest="local_json")
    agent_list = agent_sub.add_parser("list-clients", help="List the AI-client adapter catalog")
    agent_list.add_argument("--json", action="store_true", dest="local_json")
    agent_status = agent_sub.add_parser("status", help="Show managed skills and MCP registrations")
    agent_status.add_argument("--scope", choices=["project", "user"], default="project")
    agent_status.add_argument("--project", default=".")
    agent_status.add_argument("--json", action="store_true", dest="local_json")
    agent_doctor = agent_sub.add_parser("doctor", help="Validate bundled skills and perform a local MCP handshake")
    agent_doctor.add_argument("--timeout-seconds", type=float, default=10)
    agent_doctor.add_argument("--json", action="store_true", dest="local_json")
    agent_install = agent_sub.add_parser("install", help="Install only the two bundled skills and a local MCP entry")
    agent_install.add_argument("--client", default="auto")
    agent_install.add_argument("--scope", choices=["project", "user"], default="project")
    agent_install.add_argument("--project", default=".")
    agent_install.add_argument("--skills-only", action="store_true")
    agent_install.add_argument("--mcp-only", action="store_true")
    agent_install.add_argument("--copy", action="store_true", default=True)
    agent_install.add_argument("--link", action="store_true")
    agent_install.add_argument("--dry-run", action="store_true")
    agent_install.add_argument("--yes", action="store_true")
    agent_install.add_argument("--force", action="store_true")
    agent_install.add_argument("--no-backup", action="store_true")
    agent_install.add_argument("--server-name", default="codeslicer")
    agent_install.add_argument("--json", action="store_true", dest="local_json")
    for command_name, help_text in (("repair", "Restore missing managed files and the registered MCP entry"), ("uninstall", "Remove only CodeSlicer-owned files and MCP entries")):
        lifecycle = agent_sub.add_parser(command_name, help=help_text)
        lifecycle.add_argument("--scope", choices=["project", "user"], default="project")
        lifecycle.add_argument("--project", default=".")
        lifecycle.add_argument("--force", action="store_true")
        lifecycle.add_argument("--dry-run", action="store_true")
        lifecycle.add_argument("--no-backup", action="store_true")
        lifecycle.add_argument("--json", action="store_true", dest="local_json")

    adapters = sub.add_parser("adapters", help="Manage optional local evidence adapters")
    adapters_sub = adapters.add_subparsers(dest="adapter_command")
    adapters_list = adapters_sub.add_parser("list")
    adapters_list.add_argument("project")
    adapters_list.add_argument("--json", action="store_true", dest="local_json")
    adapters_preflight = adapters_sub.add_parser("preflight", help="Show the explicit local setup action for every optional adapter")
    adapters_preflight.add_argument("project")
    adapters_preflight.add_argument("adapter_id", nargs="?", default=None)
    adapters_preflight.add_argument("--json", action="store_true", dest="local_json")
    adapters_native = adapters_sub.add_parser("native", help="Discover or explicitly run an allowlisted local upstream-tool operation")
    adapters_native.add_argument("project")
    adapters_native.add_argument("adapter_id", choices=["graphify", "codegraph", "gortex", "joern", "openapi", "asyncapi", "scip", "cyclonedx", "spdx", "sarif"])
    adapters_native.add_argument("operation", nargs="?", default="profile", help="profile, probe, index, sync, status, query, context, impact, callers, callees, affected, refresh, or recipes")
    adapters_native.add_argument("--query", default="", help="Required by native query operations; never interpreted by a shell")
    adapters_native.add_argument("--confirm", action="store_true", help="Explicitly allow an operation that can create local tool state")
    adapters_native.add_argument("--timeout-seconds", type=int, default=60)
    adapters_native.add_argument("--json", action="store_true", dest="local_json")
    adapters_status = adapters_sub.add_parser("status", help="Show one optional adapter status")
    adapters_status.add_argument("project")
    adapters_status.add_argument("adapter_id")
    adapters_status.add_argument("--json", action="store_true", dest="local_json")
    adapters_import = adapters_sub.add_parser("import", help="Import one explicit local artifact for any artifact-backed adapter")
    adapters_import.add_argument("project")
    adapters_import.add_argument("adapter_id")
    adapters_import.add_argument("artifact")
    adapters_import.add_argument("--enable", action="store_true", help="Enable only after the local artifact passes validation")
    adapters_import.add_argument("--json", action="store_true", dest="local_json")
    adapters_import_scip = adapters_sub.add_parser("import-scip")
    adapters_import_scip.add_argument("project")
    adapters_import_scip.add_argument("artifact")
    adapters_import_scip.add_argument("--json", action="store_true", dest="local_json")
    adapters_enable = adapters_sub.add_parser("enable")
    adapters_enable.add_argument("project")
    adapters_enable.add_argument("adapter_id")
    adapters_enable.add_argument("--json", action="store_true", dest="local_json")
    adapters_disable = adapters_sub.add_parser("disable")
    adapters_disable.add_argument("project")
    adapters_disable.add_argument("adapter_id")
    adapters_disable.add_argument("--json", action="store_true", dest="local_json")
    adapters_verify_scip = adapters_sub.add_parser("verify-scip", help="Verify explicit local SCIP golden artifacts")
    adapters_verify_scip.add_argument("corpus", nargs="?", default=None, help="Golden corpus directory (default: repository tests/fixtures/scip/golden)")
    adapters_verify_scip.add_argument("--no-lint", action="store_true", help="Skip the official scip lint subprocess")
    adapters_verify_scip.add_argument("--json", action="store_true", dest="local_json")
    adapters_lsp = adapters_sub.add_parser("lsp", help="Configure and query an explicitly selected local Language Server")
    lsp_sub = adapters_lsp.add_subparsers(dest="lsp_command")
    lsp_status = lsp_sub.add_parser("status")
    lsp_status.add_argument("project")
    lsp_status.add_argument("--json", action="store_true", dest="local_json")
    lsp_preflight = lsp_sub.add_parser("preflight", help="Inspect local semantic readiness without starting a server")
    lsp_preflight.add_argument("project")
    lsp_preflight.add_argument("--compile-commands", default=None, help="Absolute local compilation database path")
    lsp_preflight.add_argument("--json", action="store_true", dest="local_json")
    lsp_configure = lsp_sub.add_parser("configure")
    lsp_configure.add_argument("project")
    lsp_configure.add_argument("--executable", required=True, help="Absolute local LSP or official agent-lsp executable")
    lsp_configure.add_argument("--workspace-root", action="append", required=True, dest="workspace_roots", help="Absolute allowed workspace root; repeat for multiple roots")
    lsp_configure.add_argument("--arg", action="append", default=[], dest="arguments", help="Optional local process argument; repeat as needed")
    lsp_configure.add_argument("--timeout-ms", type=int, default=5000)
    lsp_configure.add_argument("--backend", choices=["native_stdio", "agent_lsp", "auto"], default="native_stdio")
    lsp_configure.add_argument("--server-family", default="unknown")
    lsp_configure.add_argument("--compile-commands", default=None, help="Absolute local compilation database path")
    lsp_configure.add_argument("--json", action="store_true", dest="local_json")
    lsp_configure_profile = lsp_sub.add_parser("configure-profile", help="Configure one known already-installed local semantic server")
    lsp_configure_profile.add_argument("project")
    lsp_configure_profile.add_argument("profile", help="Known profile id, for example rust-analyzer or clangd")
    lsp_configure_profile.add_argument("--workspace-root", action="append", required=True, dest="workspace_roots", help="Absolute allowed workspace root; repeat for multiple roots")
    lsp_configure_profile.add_argument("--executable", default=None, help="Optional absolute local executable override; no download is attempted")
    lsp_configure_profile.add_argument("--timeout-ms", type=int, default=5000)
    lsp_configure_profile.add_argument("--compile-commands", default=None, help="Absolute local compilation database path")
    lsp_configure_profile.add_argument("--json", action="store_true", dest="local_json")
    lsp_probe = lsp_sub.add_parser("probe")
    lsp_probe.add_argument("project")
    lsp_probe.add_argument("--json", action="store_true", dest="local_json")
    lsp_start = lsp_sub.add_parser("start", help="Start or reuse the configured official Agent-LSP runtime")
    lsp_start.add_argument("project")
    lsp_start.add_argument("--json", action="store_true", dest="local_json")
    lsp_disable = lsp_sub.add_parser("disable")
    lsp_disable.add_argument("project")
    lsp_disable.add_argument("--json", action="store_true", dest="local_json")
    lsp_query = lsp_sub.add_parser("query", help="Explicitly request one bounded LSP semantic operation")
    lsp_query.add_argument("project")
    lsp_query.add_argument("--method", required=True, choices=["documentSymbol", "definition", "references", "implementation", "declaration", "typeDefinition", "hover", "workspace/symbol", "callHierarchy", "typeHierarchy", "diagnostics"])
    lsp_query.add_argument("--file", default=None)
    lsp_query.add_argument("--line", type=int, default=0)
    lsp_query.add_argument("--character", type=int, default=0)
    lsp_query.add_argument("--query", default="")
    lsp_query.add_argument("--entity-id", default=None)
    lsp_query.add_argument("--graph", default=None)
    lsp_query.add_argument("--timeout-ms", type=int, default=None)
    lsp_query.add_argument("--json", action="store_true", dest="local_json")
    for boundary_id in ("openapi", "asyncapi"):
        boundary_parser = adapters_sub.add_parser(boundary_id, help=f"Manage the local {boundary_id} boundary overlay")
        boundary_sub = boundary_parser.add_subparsers(dest="boundary_command")
        boundary_import = boundary_sub.add_parser("import")
        boundary_import.add_argument("project")
        boundary_import.add_argument("spec")
        boundary_import.add_argument("--json", action="store_true", dest="local_json")
        for action in ("enable", "disable", "status"):
            boundary_action = boundary_sub.add_parser(action)
            boundary_action.add_argument("project")
            boundary_action.add_argument("--json", action="store_true", dest="local_json")
    otel_parser = adapters_sub.add_parser("otel", help="Manage the local OpenTelemetry runtime evidence overlay")
    otel_sub = otel_parser.add_subparsers(dest="otel_command")
    otel_import = otel_sub.add_parser("import")
    otel_import.add_argument("project")
    otel_import.add_argument("trace")
    otel_import.add_argument("--json", action="store_true", dest="local_json")
    for action in ("enable", "disable", "status"):
        otel_action = otel_sub.add_parser(action)
        otel_action.add_argument("project")
        otel_action.add_argument("--json", action="store_true", dest="local_json")
    for security_id in ("cyclonedx", "spdx", "sarif"):
        security_parser = adapters_sub.add_parser(security_id, help=f"Manage the local {security_id} security evidence overlay")
        security_sub = security_parser.add_subparsers(dest="security_command")
        security_import = security_sub.add_parser("import")
        security_import.add_argument("project")
        security_import.add_argument("report")
        security_import.add_argument("--json", action="store_true", dest="local_json")
        for action in ("enable", "disable", "status"):
            security_action = security_sub.add_parser(action)
            security_action.add_argument("project")
            security_action.add_argument("--json", action="store_true", dest="local_json")
    for external_graph_id in ("graphify", "codegraph"):
        external_graph_parser = adapters_sub.add_parser(external_graph_id, help=f"Manage the local {external_graph_id} external graph overlay")
        external_graph_sub = external_graph_parser.add_subparsers(dest="external_graph_command")
        external_graph_import = external_graph_sub.add_parser("import")
        external_graph_import.add_argument("project")
        external_graph_import.add_argument("artifact")
        external_graph_import.add_argument("--json", action="store_true", dest="local_json")
        for action in ("enable", "disable", "status"):
            external_graph_action = external_graph_sub.add_parser(action)
            external_graph_action.add_argument("project")
            external_graph_action.add_argument("--json", action="store_true", dest="local_json")
    joern_parser = adapters_sub.add_parser("joern", help="Manage the explicit local Joern CPG/data-flow overlay")
    joern_sub = joern_parser.add_subparsers(dest="joern_command")
    joern_import = joern_sub.add_parser("import")
    joern_import.add_argument("project")
    joern_import.add_argument("artifact")
    joern_import.add_argument("--json", action="store_true", dest="local_json")
    joern_convert = joern_sub.add_parser("convert", help="Convert explicit local native GraphSON/CPGQL output to CodeSlicer interchange")
    joern_convert.add_argument("graphson")
    joern_convert.add_argument("--project", required=True)
    joern_convert.add_argument("--output", required=True)
    joern_convert.add_argument("--json", action="store_true", dest="local_json")
    joern_benchmark = joern_sub.add_parser("benchmark", help="Run a bounded local Joern quality benchmark")
    joern_benchmark.add_argument("project")
    joern_benchmark.add_argument("artifact")
    joern_benchmark.add_argument("--case-file", default=None, help="Absolute golden-case JSON file")
    joern_benchmark.add_argument("--case-id", default=None)
    joern_benchmark.add_argument("--output", default=None, help="Absolute aggregate report path")
    joern_benchmark.add_argument("--entity", default=None)
    joern_benchmark.add_argument("--max-nodes", type=int, default=80)
    joern_benchmark.add_argument("--max-edges", type=int, default=160)
    joern_benchmark.add_argument("--max-paths", type=int, default=40)
    joern_benchmark.add_argument("--json", action="store_true", dest="local_json")
    joern_discover = joern_sub.add_parser("discover", help="Find explicit local Joern interchange exports")
    joern_discover.add_argument("roots", nargs="+")
    joern_discover.add_argument("--max-files", type=int, default=5000)
    joern_discover.add_argument("--timeout", type=float, default=10.0, help="Maximum discovery time in seconds")
    joern_discover.add_argument("--include-synthetic", action="store_true", help="Include tests/fixtures and corpus directories")
    joern_discover.add_argument("--json", action="store_true", dest="local_json")
    for action in ("enable", "disable", "status"):
        joern_action = joern_sub.add_parser(action)
        joern_action.add_argument("project")
        joern_action.add_argument("--json", action="store_true", dest="local_json")

    quality = sub.add_parser("graph-quality")
    quality.add_argument("graph")

    unknown_regions = sub.add_parser(
        "unknown-regions",
        help="Prepare or validate evidence-gated tasks for unresolved graph regions",
    )
    unknown_regions.add_argument("project_path", nargs="?", default=None)
    unknown_regions.add_argument("--graph", default=None, help="Existing graph.json instead of re-analyzing")
    unknown_regions.add_argument("--out", default=None, help="Task JSON output path")
    unknown_regions.add_argument("--json", action="store_true", dest="local_json", help="Output JSON")

    impact = sub.add_parser("impact")
    impact.add_argument("graph_positional", nargs="?", default=None, metavar="graph.json")
    impact.add_argument("--graph", default=None)
    # Old syntax target, or new symbol/file
    impact.add_argument("--target", default=None)
    impact.add_argument("--symbol", default=None)
    impact.add_argument("--file", default=None, dest="file_arg")
    impact.add_argument("--direction", default="both", choices=["upstream", "downstream", "both"])
    impact.add_argument("--depth", type=int, default=None)
    impact.add_argument("--min-confidence", type=float, default=0.0)
    impact.add_argument("--full-context-tokens", type=int, default=None,
                        help="Measured tokens in the full repository context")
    impact.add_argument("--selected-context-tokens", type=int, default=None,
                        help="Measured tokens in the graph-selected context")

    pr_review = sub.add_parser("pr-review")
    pr_review.add_argument("project_path")
    pr_review.add_argument("--graph", default=None)
    pr_review.add_argument("--diff-file", default=None)
    pr_review.add_argument("--depth", type=int, default=6)
    pr_review.add_argument("--min-confidence", type=float, default=0.0)
    pr_review.add_argument("--max-results", type=int, default=10, help="Maximum concise impact entities (capped at 10)")
    pr_review.add_argument("--full-evidence", action="store_true", help="Explicitly include the complete impact closure for investigation")
    pr_review.add_argument("--show-potential", action="store_true", help="Explicitly include possible impact candidates, rejected relations, and coverage limitations")

    review = sub.add_parser("review", help="Build a compact local-first daily review brief")
    review.add_argument("project_path")
    review.add_argument("--base", default=None, help="Verified local or remote base ref; omit to detect safely")
    review.add_argument("--source", choices=["current-changes", "staged", "compare", "diff-file", "github-pr"], default="current-changes", help="Review source; github-pr is a reserved no-network contract")
    review.add_argument("--deep", action="store_true")
    review.add_argument("--entity", default=None, help="Entity to inspect in explicit deep mode")
    review.add_argument("--graph", default=None)
    review.add_argument("--diff-file", default=None)
    review.add_argument("--refresh", choices=["auto", "never", "force"], default="auto")
    review.add_argument("--max-results", type=int, default=10)
    review.add_argument("--run-tests", choices=["none", "suggested"], default="suggested")
    review.add_argument("--show-potential", action="store_true", help="Explicitly include possible impact candidates, rejected relations, and coverage limitations")
    review.add_argument("--json", action="store_true", dest="local_json")
    review.add_argument("--scope", default=None)
    review.add_argument("--no-daemon", action="store_true")

    inspect = sub.add_parser("inspect", help="Explain one local graph entity")
    inspect.add_argument("project_path")
    inspect.add_argument("--entity", required=True)
    inspect.add_argument("--graph", default=None)
    inspect.add_argument("--refresh", choices=["auto", "never", "force"], default="never")
    inspect.add_argument("--max-context", type=int, default=12)
    inspect.add_argument("--json", action="store_true", dest="local_json")

    investigate = sub.add_parser("investigate", help="Run an explicit bounded deep graph investigation")
    investigate.add_argument("project_path")
    investigate.add_argument("--entity", required=True)
    investigate.add_argument("--graph", default=None)
    investigate.add_argument("--direction", choices=["upstream", "downstream", "both"], default="both")
    investigate.add_argument("--depth", type=int, default=8)
    investigate.add_argument("--runtime-validate", action="store_true")
    investigate.add_argument("--max-nodes", type=int, default=500)
    investigate.add_argument("--max-edges", type=int, default=1000)
    investigate.add_argument("--refresh", choices=["auto", "never", "force"], default="never")
    investigate.add_argument("--json", action="store_true", dest="local_json")

    ci = sub.add_parser("ci", help="Evaluate the review projection with an optional CI policy")
    ci.add_argument("project_path")
    ci.add_argument("--base", default=None)
    ci.add_argument("--policy", default=None)
    ci.add_argument("--graph", default=None)
    ci.add_argument("--diff-file", default=None)
    ci.add_argument("--refresh", choices=["auto", "never", "force"], default="auto")
    ci.add_argument("--format", choices=["json", "sarif"], default="json")
    ci.add_argument("--out", default=None)
    ci.add_argument("--run-tests", action="store_true", help="Explicitly run the selected project test command")
    ci.add_argument("--test-command", nargs="+", default=None, help="Explicit test command argv; only used with --run-tests")
    ci.add_argument("--json", action="store_true", dest="local_json")

    runtime_trace = sub.add_parser("runtime-trace")
    runtime_trace.add_argument("project_path")
    runtime_trace.add_argument("--graph", default=None)
    runtime_trace.add_argument("--out", default=None)
    runtime_trace.add_argument("--timeout", type=int, default=60)

    explain = sub.add_parser("explain-edge")
    explain.add_argument("graph_positional", nargs="?", default=None, metavar="graph.json")
    explain.add_argument("--graph", default=None)
    explain.add_argument("--from", required=True, dest="from_node")
    explain.add_argument("--to", required=True, dest="to_node")
    explain.add_argument("--kind", default=None)

    # detect-languages
    det_lang = sub.add_parser("detect-languages")
    det_lang.add_argument("project_path")

    # inventory
    inv = sub.add_parser("inventory")
    inv.add_argument("project_path")

    # libraries
    libraries_parser = sub.add_parser("libraries")
    libraries_sub = libraries_parser.add_subparsers(dest="libraries_command")

    lib_detect = libraries_sub.add_parser("detect")
    lib_detect.add_argument("project_path")

    lib_research = libraries_sub.add_parser("research")
    lib_research.add_argument("project_path")
    lib_research.add_argument("--library", required=True)
    lib_research.add_argument("--ecosystem", required=True)
    lib_research.add_argument("--allow-network", action="store_true")
    lib_research.add_argument("--build-input", action="store_true")
    lib_research.add_argument("--pro", action="store_true", help="Use vendored ai_library_researcher_pro workflow")
    lib_research.add_argument("--install-draft", action="store_true", help="Stage adapted researcher-pro draft when validation succeeds")
    lib_research.add_argument("--confirm-install", action="store_true", help="Install adapted draft into the main support pack registry")
    lib_research.add_argument("--overwrite", action="store_true", help="Allow replacing an existing pack with --confirm-install")

    # support-packs
    sp_parser = sub.add_parser("support-packs")
    sp_sub = sp_parser.add_subparsers(dest="sp_command")
    sp_sub.add_parser("list")

    sp_validate = sp_sub.add_parser("validate")
    sp_validate.add_argument("path")

    sp_install = sp_sub.add_parser("install")
    sp_install.add_argument("path")
    sp_install.add_argument("--overwrite", action="store_true")

    sp_adapt = sp_sub.add_parser("adapt-pro-draft")
    sp_adapt.add_argument("path")
    sp_adapt.add_argument("--out", default=None)

    project_packs = sub.add_parser(
        "project-packs",
        help="Manage support packs scoped to one project under .impact_engine/local_packs",
    )
    project_packs_sub = project_packs.add_subparsers(dest="project_packs_command")
    project_packs_init = project_packs_sub.add_parser("init")
    project_packs_init.add_argument("project_path")
    project_packs_list = project_packs_sub.add_parser("list")
    project_packs_list.add_argument("project_path")
    project_packs_install = project_packs_sub.add_parser("install")
    project_packs_install.add_argument("project_path")
    project_packs_install.add_argument("pack_path")
    project_packs_install.add_argument("--trust-level", default="draft")
    project_packs_install.add_argument("--overwrite", action="store_true")

    # db
    db_parser = sub.add_parser("db")
    db_sub = db_parser.add_subparsers(dest="db_command")

    db_init = db_sub.add_parser("init")
    db_init.add_argument("--path", default=None)

    db_runs = db_sub.add_parser("runs")
    db_runs.add_argument("--path", default=None)

    # research
    research_parser = sub.add_parser("research")
    research_sub = research_parser.add_subparsers(dest="research_command")

    r_start = research_sub.add_parser("start")
    r_start.add_argument("project_path")
    r_start.add_argument("--library", required=True)
    r_start.add_argument("--ecosystem", required=True)

    r_fetch = research_sub.add_parser("fetch")
    r_fetch.add_argument("workflow_id")

    r_build = research_sub.add_parser("build-input")
    r_build.add_argument("workflow_id")

    r_validate = research_sub.add_parser("validate")
    r_validate.add_argument("workflow_id")
    r_validate.add_argument("support_pack")

    r_install = research_sub.add_parser("install")
    r_install.add_argument("workflow_id")
    r_install.add_argument("support_pack")

    # doctor
    doctor = sub.add_parser("doctor")
    doctor.add_argument("--full", action="store_true", help="Verify wheel/runtime assets in addition to local capabilities")

    approvals = sub.add_parser("approvals", help="List and approve one-time local action requests")
    approvals_sub = approvals.add_subparsers(dest="approvals_command", required=True)
    approvals_list = approvals_sub.add_parser("list")
    approvals_list.add_argument("project_path")
    approvals_show = approvals_sub.add_parser("show")
    approvals_show.add_argument("project_path")
    approvals_show.add_argument("approval_id")
    approvals_approve = approvals_sub.add_parser("approve")
    approvals_approve.add_argument("project_path")
    approvals_approve.add_argument("approval_id")

    # local registry
    registry_parser = sub.add_parser("registry")
    registry_sub = registry_parser.add_subparsers(dest="registry_command")
    registry_sub.add_parser("status")

    registry_cache_pack = registry_sub.add_parser("cache-pack")
    registry_cache_pack.add_argument("path")

    registry_pull_pack = registry_sub.add_parser("pull-pack")
    registry_pull_pack.add_argument("ecosystem")
    registry_pull_pack.add_argument("library")

    registry_research = registry_sub.add_parser("create-research-request")
    registry_research.add_argument("--ecosystem", required=True)
    registry_research.add_argument("--library", required=True)
    registry_research.add_argument("--package", default=None, dest="package_name")
    registry_research.add_argument("--project-fingerprint", default=None)

    registry_sync = registry_sub.add_parser("sync-project")
    registry_sync.add_argument("project_path")
    registry_sync.add_argument("--no-research-requests", action="store_true")

    registry_worker = registry_sub.add_parser("process-queue")
    registry_worker.add_argument("project_path")
    registry_worker.add_argument("--limit", type=int, default=20)
    registry_worker.add_argument("--allow-network", action="store_true")

    registry_register = registry_sub.add_parser("register-library")
    registry_register.add_argument("ecosystem")
    registry_register.add_argument("library")
    registry_register.add_argument("--docs-url", default=None)
    registry_register.add_argument("--repository-url", default=None)
    registry_register.add_argument("--package-manager", default=None)

    registry_status_library = registry_sub.add_parser("library-status")
    registry_status_library.add_argument("ecosystem")
    registry_status_library.add_argument("library")

    registry_approve = registry_sub.add_parser("approve-pack")
    registry_approve.add_argument("pack_id")
    registry_approve.add_argument("--trust-level", required=True)
    registry_approve.add_argument("--reviewer", required=True)
    registry_approve.add_argument("--note", default=None)

    registry_doc_check = registry_sub.add_parser("doc-check")
    registry_doc_check.add_argument("ecosystem")
    registry_doc_check.add_argument("library")
    registry_doc_check.add_argument("url")
    registry_doc_check.add_argument("--content-hash", required=True)
    registry_doc_check.add_argument("--source-type", default="docs")

    registry_simulate = registry_sub.add_parser("simulate-lifecycle")
    registry_simulate.add_argument("ecosystem")
    registry_simulate.add_argument("library")
    registry_simulate.add_argument("--source-url", required=True)

    # qa
    qa_parser = sub.add_parser("qa")
    qa_sub = qa_parser.add_subparsers(dest="qa_command")
    qa_run = qa_sub.add_parser("run")
    qa_run.add_argument("projects_root")
    qa_run.add_argument("--out-dir", default=None)

    benchmark_parser = sub.add_parser("benchmark")
    benchmark_sub = benchmark_parser.add_subparsers(dest="benchmark_command")
    benchmark_run = benchmark_sub.add_parser("run")
    benchmark_run.add_argument("root")
    benchmark_det = benchmark_sub.add_parser("determinism")
    benchmark_det.add_argument("project_path")
    benchmark_det.add_argument("--runs", type=int, default=3)
    benchmark_mutate = benchmark_sub.add_parser("mutate")
    benchmark_mutate.add_argument("root")
    benchmark_libraries = benchmark_sub.add_parser("libraries")
    benchmark_libraries.add_argument("root", nargs="?", default=".")
    benchmark_typescript = benchmark_sub.add_parser("typescript")
    benchmark_typescript.add_argument("root", nargs="?", default=".")
    benchmark_typescript_source = benchmark_sub.add_parser("typescript-source")
    benchmark_typescript_source.add_argument("root", nargs="?", default=".")
    benchmark_research_e2e = benchmark_sub.add_parser("research-e2e")
    benchmark_research_e2e.add_argument("root", nargs="?", default=".")
    benchmark_polyglot = benchmark_sub.add_parser("polyglot")
    benchmark_polyglot.add_argument("root", nargs="?", default=".")

    return parser
