export const clientRouter = String.raw`const vscode=typeof acquireVsCodeApi==='function'?acquireVsCodeApi():{getState:()=>undefined,setState:()=>undefined,postMessage:()=>undefined};
const tabs=['start','review','results','tests','tech','history','architecture','git','settings'];let currentTab=(vscode.getState()||{}).tab||'start';let demoStep=0;
const byId=id=>document.getElementById(id);
function selectTab(id,focus){if(!tabs.includes(id))return;currentTab=id;document.querySelectorAll('[role=tab]').forEach(tab=>{const selected=tab.dataset.tab===id;tab.setAttribute('aria-selected',String(selected));const panel=byId('panel-'+tab.dataset.tab);if(panel)panel.hidden=!selected});vscode.setState({tab:id});if(focus)document.querySelector('[data-tab="'+id+'"]')?.focus()}
function say(title,text){byId('demo-title').textContent=title;byId('demo-text').textContent=text}
function stopDemo(){byId('demo-guide').hidden=true}
function showDemoStep(step){demoStep=step;const flow=[['1/7 · Проверка','Выбираем источник локальных изменений и базовую ветку main. Никакая команда не запускается.','review'],['2/7 · Результат','Здесь появляются риск, причины и подтверждённые evidence chains.','results'],['3/7 · Тесты','Рекомендации показываются отдельно; настоящий тест всегда требует подтверждения.','tests'],['4/7 · Технологии','Видно встроенное покрытие и честный статус optional packs.','tech'],['5/7 · История','Все summaries остаются только в local workspace state.','history'],['6/7 · Код','Полная карта доступна в Local Hub. Graphify остаётся отдельным optional engine.','architecture'],['7/7 · Git cockpit','Сначала обновляем дерево, затем проверяем точное направление push. Force push не предусмотрен.','git'],['Гид завершён','Вы увидели весь сценарий. Ваш проект не менялся и ни один процесс не запускался.','start']][step]||[];say(flow[0]||'',flow[1]||'');selectTab(flow[2]||'start',true)}
function startDemo(){byId('demo-guide').hidden=false;showDemoStep(0)}
document.addEventListener('click',event=>{const target=event.target?.closest?.('button');if(!target)return;if(target.dataset.language)return vscode.postMessage({type:'setLanguage',language:target.dataset.language});if(target.dataset.tab)return selectTab(target.dataset.tab,true);if(target.dataset.demoStart!==undefined)return startDemo();if(target.dataset.demoNext!==undefined)return showDemoStep(Math.min(demoStep+1,7));if(target.dataset.demoStop!==undefined)return stopDemo();if(target.dataset.action)return vscode.postMessage({type:'action',action:target.dataset.action});if(target.dataset.test!==undefined)return vscode.postMessage({type:'runTest',index:Number(target.dataset.test)});if(target.dataset.entity)return vscode.postMessage({type:'entity',entity:target.dataset.entity,file:target.dataset.file,line:Number(target.dataset.line)||undefined})});
if(typeof window!=='undefined')window.addEventListener('message',event=>{if(event.data?.type==='showDemo')startDemo()});selectTab(currentTab,false);`;
