export const clientRouter = String.raw`const vscode=typeof acquireVsCodeApi==='function'?acquireVsCodeApi():{getState:()=>undefined,setState:()=>undefined,postMessage:()=>undefined};
const saved=vscode.getState()||{};
const language=document.documentElement.lang==='ru'?'ru':'en';
const labels={ru:{step:'Шаг',of:'из',next:'Далее',done:'Завершить',install:'Установить за пару кликов',skills:'Подключить IDE и skills',review:'Проверить свои изменения',compare:'Сравнить с веткой',architecture:'Разобраться в архитектуре',pr:'Проверить GitHub PR'},en:{step:'Step',of:'of',next:'Next',done:'Finish',install:'Install in a couple of clicks',skills:'Connect IDE and skills',review:'Review my changes',compare:'Compare with a branch',architecture:'Understand the architecture',pr:'Review a GitHub PR'}}[language];
const courses={ru:{
install:{summary:'Установите CodeSlicer без поиска команд, выбора папки и ручного указания executable.',steps:[
{tab:'settings',target:'[data-action="installRuntime"]',title:'Установите CodeSlicer автоматически',text:'Одно нажатие скачивает CodeSlicer в служебную папку VS Code, создаёт локальную среду и сразу подключает executable.',tip:'Папки и пути выбирать не нужно; установка начинается только после вашего нажатия.',action:'installRuntime',actionLabel:'Установить CodeSlicer'},
{tab:'settings',target:'[data-action="setupSkills"]',title:'При желании выберите IDE и skills',text:'Откройте короткое меню PowerShell и отметьте только те IDE, для которых нужны skills.',tip:'Это необязательный второй шаг: базовая установка уже готова.',action:'setupSkills',actionLabel:'Выбрать IDE и skills'}]},
skills:{summary:'Выберите IDE в интерактивном PowerShell-меню и установите два CodeSlicer skills в безопасные папки выбранного клиента.',steps:[
{tab:'settings',target:'[data-action="setupSkills"]',title:'Откройте выбор IDE',text:'Кнопка откроет PowerShell только после подтверждения. В нём используйте ↑/↓ для перемещения, Space для выбора IDE и Enter для установки.',tip:'Установщик показывает поддерживаемые IDE и меняет только выбранные integration-файлы.',action:'setupSkills',actionLabel:'Открыть выбор IDE и skills'},
{tab:'settings',target:'[data-action="setupSkills"]',title:'Подтвердите выбранные IDE',text:'Отметьте одну или несколько IDE. По умолчанию skills ставятся в user scope, поэтому будут доступны в следующих проектах.',tip:'Перед изменением существующего MCP-файла установщик делает рядом резервную копию.',action:'setupSkills',actionLabel:'Открыть меню ещё раз'},
{tab:'check',target:'#panel-check',title:'Перезапустите IDE и начните работу',text:'После завершения закройте и снова откройте выбранную IDE, затем откройте свой проект и попросите агента проверить изменения.',tip:'Skills описывают workflow; CodeSlicer запускается только по явному действию агента или команды.'}]},
review:{summary:'Научитесь получать локальный отчёт о текущих Git-изменениях и использовать его перед merge.',steps:[{tab:'check',target:'[data-action="configureBase"]',title:'Уточните базовую ветку',text:'CodeSlicer сравнивает изменения с локальной базовой веткой. Если она определилась верно, переходите дальше; иначе выберите её вручную.',tip:'Это только настройка сравнения — анализ ещё не запускается.',action:'configureBase',actionLabel:'Выбрать базовую ветку'},{tab:'check',target:'[data-action="review"]',title:'Запустите локальную проверку',text:'Когда рабочая папка доверена и runtime настроен, запустите проверку текущих изменений.',tip:'Проверка выполняется локально. Действие запускается только по кнопке ниже.',action:'review',actionLabel:'Проверить текущие изменения'},{tab:'result',target:'#panel-result',title:'Прочитайте риск и доказательства',text:'После проверки здесь будут уровень риска, затронутые сущности и ссылки на доказательства.',tip:'Этот шаг только открывает вкладку и ничего не меняет.'},{tab:'tests',target:'#panel-tests',title:'Выберите следующий тест',text:'Откройте рекомендованные тесты и запустите нужный только после просмотра команды.',tip:'Перед реальным запуском теста CodeSlicer попросит подтверждение.'}]},
compare:{summary:'Настройте явную базовую ветку и получите отчёт именно для сравнения с ней.',steps:[{tab:'settings',target:'[data-action="configureBase"]',title:'Укажите ветку для сравнения',text:'Выберите существующую локальную ветку, например main или release/1.2.',tip:'CodeSlicer проверит, что ref безопасен и существует локально.',action:'configureBase',actionLabel:'Указать базовую ветку'},{tab:'check',target:'#panel-check',title:'Выберите сценарий сравнения',text:'На вкладке Проверка выберите «Сравнение refs / diff».',tip:'Если эта кнопка ещё не видна, сначала выполните обычную проверку текущих изменений.',action:'sourceCompare',actionLabel:'Выбрать сравнение'},{tab:'check',target:'[data-action="review"]',title:'Запустите проверку',text:'Проверьте выбранное сравнение и дождитесь локального отчёта.',tip:'Команда не отправляет исходный код во внешние сервисы.',action:'review',actionLabel:'Запустить проверку'},{tab:'result',target:'#panel-result',title:'Сравните результат',text:'Просмотрите риск, затронутые сущности и доказательства для выбранной базы.',tip:'Переход на эту вкладку безопасен и ничего не запускает.'}]},
architecture:{summary:'Подключите уже подготовленную карту Graphify, а затем откройте её в локальном обзоре.',steps:[{tab:'settings',target:'[data-action="configureGraphify"]',title:'Выберите готовый graph.json',text:'Укажите существующий файл Graphify graph.json. CodeSlicer не создаёт его автоматически.',tip:'Архитектурная карта остаётся отдельной от доказательств CodeSlicer.',action:'configureGraphify',actionLabel:'Выбрать graph.json'},{tab:'architecture',target:'#panel-architecture',title:'Откройте вкладку Архитектура',text:'Здесь видно, что карта подключена как отдельный архитектурный контекст.',tip:'Открытие вкладки не меняет файлы и не запускает Graphify.'},{tab:'architecture',target:'[data-action="hub"]',title:'Откройте локальный обзор',text:'Откройте уже запущенный локальный hub, чтобы посмотреть карту в браузере.',tip:'Адрес ограничен localhost для безопасности.',action:'hub',actionLabel:'Открыть локальный обзор'}]},
pr:{summary:'Получите diff pull request через OAuth и выполните проверку локально, не публикуя результаты.',steps:[{tab:'check',target:'#panel-check',title:'Подготовьте рабочую папку',text:'Откройте папку проекта в VS Code и убедитесь, что workspace доверен.',tip:'OAuth и сетевые запросы не начнутся до отдельного действия.'},{tab:'check',target:'#panel-check',title:'Укажите GitHub pull request',text:'Откройте форму PR и вставьте канонический URL вида github.com/owner/repository/pull/42.',tip:'CodeSlicer использует OAuth только после вашего продолжения.',action:'sourceGitHub',actionLabel:'Открыть форму GitHub PR'},{tab:'check',target:'[data-action="review"]',title:'Запустите локальную проверку diff',text:'После загрузки diff выберите проверку — CodeSlicer работает с сохранённым локальным файлом.',tip:'Результаты review не публикуются в GitHub.',action:'review',actionLabel:'Проверить PR локально'},{tab:'result',target:'#panel-result',title:'Разберите результат',text:'Посмотрите риск, затронутые сущности и доказательства перед тем, как оставлять review.',tip:'Вкладка Результат безопасна для просмотра.'}]}},
en:{
install:{summary:'Install CodeSlicer without hunting for commands, choosing a folder, or setting an executable path manually.',steps:[
{tab:'settings',target:'[data-action="installRuntime"]',title:'Install CodeSlicer automatically',text:'One click downloads CodeSlicer into VS Code private storage, creates the local environment, and connects its executable.',tip:'You do not need to choose folders or paths; installation starts only after your click.',action:'installRuntime',actionLabel:'Install CodeSlicer'},
{tab:'settings',target:'[data-action="setupSkills"]',title:'Optionally choose IDEs and skills',text:'Open the short PowerShell menu and select only the IDEs that need skills.',tip:'This optional second step is separate from the finished base install.',action:'setupSkills',actionLabel:'Choose IDE and skills'}]},
skills:{summary:'Choose an IDE in an interactive PowerShell menu and install the two CodeSlicer skills into safe locations for that client.',steps:[
{tab:'settings',target:'[data-action="setupSkills"]',title:'Open the IDE picker',text:'The button opens PowerShell only after confirmation. Use ↑/↓ to move, Space to select IDEs, and Enter to install.',tip:'The installer lists supported IDEs and changes only integration files for the choices you make.',action:'setupSkills',actionLabel:'Open IDE and skills picker'},
{tab:'settings',target:'[data-action="setupSkills"]',title:'Confirm the selected IDEs',text:'Select one or more IDEs. Skills use user scope by default, so they remain available in later projects.',tip:'The installer makes a nearby backup before changing an existing MCP file.',action:'setupSkills',actionLabel:'Open the menu again'},
{tab:'check',target:'#panel-check',title:'Restart the IDE and begin',text:'When it finishes, restart the selected IDE, open your project, and ask its agent to review the changes.',tip:'Skills describe the workflow; CodeSlicer runs only from an explicit agent or command action.'}]},
review:{summary:'Learn how to produce a local report for current Git changes and use it before merge.',steps:[{tab:'check',target:'[data-action="configureBase"]',title:'Confirm the base branch',text:'CodeSlicer compares your changes with a local base branch. Continue if it is correct, or choose one yourself.',tip:'This only configures comparison; analysis has not started.',action:'configureBase',actionLabel:'Choose base branch'},{tab:'check',target:'[data-action="review"]',title:'Start a local review',text:'When the workspace is trusted and the runtime is configured, review current changes.',tip:'The review runs locally and starts only from the action below.',action:'review',actionLabel:'Review current changes'},{tab:'result',target:'#panel-result',title:'Read risk and evidence',text:'After a review this tab shows risk, affected entities, and evidence.',tip:'This step only opens a tab.'},{tab:'tests',target:'#panel-tests',title:'Choose the next test',text:'Open recommended tests and run one only after reviewing its command.',tip:'CodeSlicer asks for confirmation before a real test runs.'}]},
compare:{summary:'Set an explicit base branch and review changes against that branch.',steps:[{tab:'settings',target:'[data-action="configureBase"]',title:'Set the comparison branch',text:'Choose an existing local branch such as main or release/1.2.',tip:'CodeSlicer verifies that the ref is safe and exists locally.',action:'configureBase',actionLabel:'Set base branch'},{tab:'check',target:'#panel-check',title:'Choose compare mode',text:'On the Check tab choose Compare refs / diff.',tip:'If this button is not visible yet, run a normal current-changes review first.',action:'sourceCompare',actionLabel:'Choose comparison'},{tab:'check',target:'[data-action="review"]',title:'Start the review',text:'Review the selected comparison and wait for the local report.',tip:'The command does not upload source code to external services.',action:'review',actionLabel:'Start review'},{tab:'result',target:'#panel-result',title:'Compare the result',text:'Review risk, affected entities, and evidence for the selected base.',tip:'Opening this tab is safe and does not start work.'}]},
architecture:{summary:'Connect an existing Graphify map, then open it in the local overview.',steps:[{tab:'settings',target:'[data-action="configureGraphify"]',title:'Choose an existing graph.json',text:'Select an existing Graphify graph.json file. CodeSlicer never creates it automatically.',tip:'The architecture map remains separate from CodeSlicer evidence.',action:'configureGraphify',actionLabel:'Choose graph.json'},{tab:'architecture',target:'#panel-architecture',title:'Open the Architecture tab',text:'This tab shows the map as separate architecture context.',tip:'Opening it does not change files or run Graphify.'},{tab:'architecture',target:'[data-action="hub"]',title:'Open the local overview',text:'Open an already running local hub to view the map in your browser.',tip:'For safety the address is limited to localhost.',action:'hub',actionLabel:'Open local overview'}]},
pr:{summary:'Fetch a pull-request diff through OAuth and review it locally without publishing results.',steps:[{tab:'check',target:'#panel-check',title:'Prepare the workspace',text:'Open the project folder in VS Code and make sure the workspace is trusted.',tip:'OAuth and network requests do not start before a separate action.'},{tab:'check',target:'#panel-check',title:'Enter the GitHub pull request',text:'Open the PR form and paste a canonical URL such as github.com/owner/repository/pull/42.',tip:'CodeSlicer starts OAuth only after you continue.',action:'sourceGitHub',actionLabel:'Open GitHub PR form'},{tab:'check',target:'[data-action="review"]',title:'Review the local diff',text:'After the diff is ready, start review. CodeSlicer uses the locally saved file.',tip:'Review results are not published to GitHub.',action:'review',actionLabel:'Review PR locally'},{tab:'result',target:'#panel-result',title:'Read the result',text:'Review risk, affected entities, and evidence before leaving feedback.',tip:'The Result tab is safe to view.'}]}}}[language];
let onboardingSeen=saved.onboardingSeen===true;let currentTab=onboardingSeen?(saved.tab||'check'):'learn';let courseId=saved.course&&courses[saved.course]?saved.course:undefined;let courseIndex=Number.isInteger(saved.courseIndex)?saved.courseIndex:0;let focused;
function byId(id){return document.getElementById(id)}
function save(){vscode.setState({tab:currentTab,course:courseId,courseIndex:courseIndex,onboardingSeen:onboardingSeen})}
function clearFocus(){if(focused)focused.classList.remove('guide-focus');focused=undefined}
function guidePanel(active){const panel=byId('panel-learn');if(panel)panel.classList.toggle('guide-active',active)}
function selectTab(id,moveFocus){const next=byId('panel-'+id);if(!next)return;currentTab=id;document.querySelectorAll('[role=tab]').forEach(item=>{const selected=item.dataset.tab===id;item.setAttribute('aria-selected',String(selected));const panel=byId('panel-'+item.dataset.tab);if(panel)panel.hidden=!selected});save();if(moveFocus){const tabButton=document.querySelector('[data-tab="'+id+'"]');if(tabButton)tabButton.focus()}}
function course(){return courseId?courses[courseId]:undefined}
function renderProgress(model){const progress=byId('course-progress');progress.textContent='';model.steps.forEach((item,index)=>{const element=document.createElement('li');if(index===courseIndex)element.setAttribute('aria-current','step');const number=document.createElement('span');number.className='progress-index';number.textContent=String(index+1);const text=document.createElement('span');text.textContent=item.title;element.append(number,text);progress.append(element)})}
function renderCourse(){const model=course();if(!model)return;courseIndex=Math.max(0,Math.min(courseIndex,model.steps.length-1));byId('learning-home').hidden=true;byId('learning-course').hidden=false;const step=model.steps[courseIndex];byId('course-kicker').textContent=labels[courseId];byId('course-title').textContent=labels[courseId];byId('course-summary').textContent=model.summary;byId('course-step-count').textContent=labels.step+' '+(courseIndex+1)+' '+labels.of+' '+model.steps.length;byId('course-step-title').textContent=step.title;byId('course-step-text').textContent=step.text;byId('course-tip').textContent=step.tip;renderProgress(model);const perform=byId('course-perform');perform.hidden=!step.action;if(step.action){perform.textContent=step.actionLabel;perform.dataset.action=step.action}else delete perform.dataset.action;const next=byId('course-next'),last=courseIndex===model.steps.length-1;next.textContent=last?labels.done:labels.next;save()}
function openLearning(){clearFocus();guidePanel(false);courseId=undefined;courseIndex=0;selectTab('learn',true);byId('learning-home').hidden=false;byId('learning-course').hidden=true;save()}
function openCourse(id){if(!courses[id])return;clearFocus();onboardingSeen=true;courseId=id;courseIndex=0;renderCourse();guidePanel(true);showTarget()}
function showTarget(){const model=course();if(!model)return;const step=model.steps[courseIndex];selectTab(step.tab,true);clearFocus();const target=document.querySelector(step.target);if(target){focused=target;focused.classList.add('guide-focus');focused.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}}
function performStep(){const model=course();if(!model)return;const action=model.steps[courseIndex].action;if(action)vscode.postMessage({type:'action',action:action})}
document.addEventListener('click',event=>{const target=event.target&&typeof event.target.closest==='function'?event.target.closest('button'):undefined;if(!target)return;if(target.dataset.course){openCourse(target.dataset.course);return}if(target.dataset.learning){if(target.dataset.learning==='home')openLearning();else if(target.dataset.learning==='back'&&courseIndex>0){courseIndex--;renderCourse();showTarget()}else if(target.dataset.learning==='next'){const model=course();if(courseIndex===model.steps.length-1)openLearning();else{courseIndex++;renderCourse();showTarget()}}else if(target.dataset.learning==='show')showTarget();else if(target.dataset.learning==='perform')performStep();return}if(target.dataset.tab){onboardingSeen=true;selectTab(target.dataset.tab,true);return}if(target.dataset.action==='learn'){openLearning();return}if(target.dataset.action){vscode.postMessage({type:'action',action:target.dataset.action});return}if(target.dataset.test!==undefined){vscode.postMessage({type:'runTest',index:Number(target.dataset.test)});return}if(target.dataset.entity){vscode.postMessage({type:'entity',entity:target.dataset.entity,file:target.dataset.file,line:Number(target.dataset.line)||undefined})}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&courseId){event.preventDefault();openLearning()}});selectTab(currentTab,false);if(courseId){renderCourse();guidePanel(true);showTarget()}`;
