from project_semantics_hygiene import FileRole, FileRoleClassifier, ProjectFile


def test_generated_path_detection():
    fc = FileRoleClassifier().classify_path("frontend/src/__generated__/api.generated.ts")
    assert fc.role is FileRole.GENERATED
    assert fc.is_generated is True
    assert fc.language == "typescript"
    assert fc.confidence >= 0.9


def test_generated_content_marker_detection():
    content = "// Code generated by tool. DO NOT EDIT\nexport const x = 1;"
    fc = FileRoleClassifier().classify_path("src/client.ts", content)
    assert fc.role is FileRole.GENERATED
    assert any("generated marker" in r for r in fc.reasons)


def test_pytest_vitest_go_java_tests():
    classifier = FileRoleClassifier()
    assert classifier.classify_path("tests/test_orders.py").role is FileRole.TEST
    assert classifier.classify_path("frontend/src/order.test.tsx").role is FileRole.TEST
    assert classifier.classify_path("store/user_test.go").role is FileRole.TEST
    assert classifier.classify_path("src/UserServiceTest.java").role is FileRole.TEST


def test_contract_schema_detection():
    classifier = FileRoleClassifier()
    assert classifier.classify_path("contracts/openapi.json").role is FileRole.CONTRACT
    assert classifier.classify_path("schemas/user.schema.json").role is FileRole.CONTRACT
    assert classifier.classify_path("api/graphql.schema").role is FileRole.CONTRACT
    assert classifier.classify_path("contracts/order.proto").role is FileRole.CONTRACT


def test_config_docs_vendor_migration_fixture_detection():
    classifier = FileRoleClassifier()
    assert classifier.classify_path("pyproject.toml").role is FileRole.CONFIG
    assert classifier.classify_path("frontend/vite.config.ts").role is FileRole.CONFIG
    assert classifier.classify_path("README.md").role is FileRole.DOCS
    assert classifier.classify_path("docs/architecture.md").role is FileRole.DOCS
    assert classifier.classify_path("node_modules/react/index.js").role is FileRole.VENDOR
    assert classifier.classify_path("dist/app.bundle.js").role is FileRole.BUILD_ARTIFACT
    assert classifier.classify_path("migrations/202601010101_add_users.py").role is FileRole.MIGRATION
    assert classifier.classify_path("tests/fixtures/accounts.json").role is FileRole.TEST  # test has priority over fixture
    assert classifier.classify_path("fixtures/accounts.json").role is FileRole.FIXTURE


def test_dead_legacy_only_tags_not_role():
    classifier = FileRoleClassifier()
    fc = classifier.classify_path("backend/services/dead_legacy_order_service.py")
    assert fc.role is FileRole.SOURCE
    assert "dead_candidate" in fc.tags
    assert "legacy_candidate" in fc.tags


def test_priority_generated_over_source_and_test():
    classifier = FileRoleClassifier()
    fc = classifier.classify_path("tests/__generated__/client.ts", "// normal")
    assert fc.role is FileRole.GENERATED


def test_language_detection():
    classifier = FileRoleClassifier()
    assert classifier.classify_path("a.py").language == "python"
    assert classifier.classify_path("a.tsx").language == "typescript"
    assert classifier.classify_path("a.go").language == "go"
    assert classifier.classify_path("a.java").language == "java"
    assert classifier.classify_path("a.yaml").language == "yaml"
