import assert from"node:assert/strict";import{mkdtemp,writeFile}from"node:fs/promises";import{tmpdir}from"node:os";import{join}from"node:path";import{createHash}from"node:crypto";import test from"node:test";import{buildAnalyzeArgs,buildReviewArgs,safeTestCommand}from"../src/cli";import{isSafeRef}from"../src/runtime";import{parseJsonLineProgress}from"../src/progress";import{CodeSlicerRuntimeManager,runtimeTarget,validateRuntimeFiles}from"../src/runtime-manager";
test("CodeSlicer commands put the global JSON argument before the subcommand and never ask it to run tests",()=>{assert.deepEqual(buildReviewArgs("C:/project with spaces",{mode:"current-changes"},"main"),["--json","review","C:/project with spaces","--source","current-changes","--base","main","--max-results","10","--run-tests","none","--refresh","auto","--no-daemon"]);assert.deepEqual(buildReviewArgs("C:/project",{mode:"diff-file",diffFile:"C:/review.patch"}),["--json","review","C:/project","--source","diff-file","--diff-file","C:/review.patch","--max-results","10","--run-tests","none","--refresh","auto","--no-daemon"]);assert.deepEqual(buildAnalyzeArgs("C:/project"),["--json","analyze","C:/project","--use-scan-plan","--progress","jsonl","--no-daemon"])});
test("base refs reject options and traversal-like values",()=>{assert.equal(isSafeRef("main"),true);assert.equal(isSafeRef("release/1.2"),true);assert.equal(isSafeRef("--upload"),false);assert.equal(isSafeRef("main..other"),false)});
test("runtime selection is constrained to supported VS Code platform targets",()=>{assert.equal(runtimeTarget("win32","x64"),"win32-x64");assert.equal(runtimeTarget("linux","arm64"),"linux-arm64");assert.equal(runtimeTarget("freebsd","x64"),undefined)});
test("only a safe argv test command is accepted",()=>{assert.deepEqual(safeTestCommand(["py","-3","-m","pytest","tests/test_api.py"]),["py","-3","-m","pytest","tests/test_api.py"]);assert.equal(safeTestCommand("pytest tests/test_api.py"),undefined);assert.equal(safeTestCommand(["powershell","-Command","pytest"]),undefined)});
test("runtime location belongs to the extension VSIX",()=>{const runtime=new CodeSlicerRuntimeManager("C:/extension");assert.match(runtime.runtimePath()||"",/extension.*runtime/u)});
test("runtime installation status promises no download or system Python setup",()=>{const runtime=new CodeSlicerRuntimeManager("C:/extension");assert.match(runtime.installationAvailability(),/never downloads.*virtual environment.*pip/u)});
test("runtime manifest verifies every declared file and rejects traversal",async()=>{const root=await mkdtemp(join(tmpdir(),"codeslicer-runtime-"));const file=join(root,"bin.exe");await writeFile(file,"runtime");const hash=createHash("sha256").update("runtime").digest("hex");assert.equal(await validateRuntimeFiles(root,{"bin.exe":hash}),undefined);assert.match(await validateRuntimeFiles(root,{"bin.exe":"0".repeat(64)})||"",/checksum/u);assert.match(await validateRuntimeFiles(root,{"../escape":hash})||"",/unsafe/u)});
test("JSON Lines progress ignores ordinary diagnostics",()=>{assert.deepEqual(parseJsonLineProgress('warning\n{"type":"progress","overall_percent":50,"message":"Extracting"}'),[{type:"progress",overall_percent:50,message:"Extracting"}])});
